
title: "Stepwise_Machine_Learning_Model"
"
author: "Subhamoy"


library(gtsummary)
library(MASS)
library(sjlabelled)
library(tidyverse)
library(caret)
library(dplyr)
library(readr)
#Final_Merged <- read_csv("Downloads/2023-08-24 Final Merged.csv")
library(readxl)
library(readxl)
library(VIM)
library(car)
library(mice)
library(ggpubr)

Biomarker_demo <- read_excel("Downloads/Biomarker_demo.xlsx")
Biomarker_Biom <- read_excel("Downloads/Biomarker_Biom.xlsx")
Final_Merged = left_join(Biomarker_demo, Biomarker_Biom, by= c('ID' = 'ID', 'madc_dx' = 'madc_dx'))
Biomarker_Comorbidities <- read_excel("Downloads/Biomarker_Comorbidities.xlsx")
Biomarker_Data = left_join(Final_Merged, Biomarker_Comorbidities, by= c('ID' = 'ID', 'madc_dx' = 'madc_dx'))


table(Biomarker_Data$madc_dx)




library("gtsummary")
Biomarker_Data2 <- Biomarker_Data %>% filter(Cognitive_Status == "Cognitively unimpaired" | Cognitive_Status == "MCI" | Cognitive_Status == "AD") %>% filter(Race == "White" | Race == "Black") %>% dplyr::select(Cognitive_Status, tau, pT181, aBeta42, aBeta40, `aBeta 42:40`, pT217, GFAP, NfL, APOE_Coll, BMI, Age, Race, sex,  Education_Coll, Stroke,	Cancer,	Diabetes,	MI, `Depression in last 2yrs`,	Hypertension,	Hypercholesterolemia,	`Sleep Apnea`,	`Atrial Fibrillation`)
Biomarker_Data2 %>% tbl_summary(missing_text = "(Missing)", label = c(BMI ~ "BMI (pg/mL)", tau ~ "tTau (pg/mL)", pT181 ~ "pT181 (pg/mL)", aBeta42 ~ "aB42 (pg/mL)", aBeta40 ~ "aB40 (pg/mL)", `aBeta 42:40` ~ "aBeta 42:40", GFAP ~ "GFAP (pg/mL)",pT217 ~ "pT217 (pg/mL)", NfL ~ "NfL (pg/mL)", Education_Coll ~ "Education", APOE_Coll ~ "APOE" ), digits = list(everything() ~ c(3))) %>% bold_labels() %>% modify_caption("**Summary table**")


Biomarker_Data2 %>% filter(Cognitive_Status == "Cognitively unimpaired" | Cognitive_Status == "MCI" | Cognitive_Status == "AD") %>% filter(Race == "White" | Race == "Black") %>%
  tbl_summary(
    by = Cognitive_Status,
    statistic = list(all_continuous() ~ "{mean} ({sd}) | {median} ({IQR})",
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    digits = list(everything() ~ c(3)),
    label = c(BMI ~ "BMI (pg/mL)", tau ~ "tTau (pg/mL)", pT181 ~ "pT181 (pg/mL)", aBeta42 ~ "aB42 (pg/mL)", aBeta40 ~ "aB40 (pg/mL)", GFAP ~ "GFAP (pg/mL)", NfL ~ "NfL (pg/mL)", pT217 ~ "pT217 (pg/mL)", Education_Coll ~ "Education", APOE_Coll ~ "APOE", `aBeta 42:40` ~ "aBeta 42:40" ),
    missing_text = "(Missing)"
  ) %>% add_p() %>% bold_labels() %>% modify_caption("**Summary table: Different cognitive status**")



datamat1 = cor(Data_corr[,c(2,3,4,5,6,11, 12, 13)], use="pairwise.complete.obs")
colnames(datamat1) = c("tau", "pT181", "aB42", "aB40", "a42:40", "GFAP", "NfL" , "pT217")
rownames(datamat1) = c("tau", "pT181", "aB42", "aB40", "a42:40", "GFAP", "NfL" , "pT217")
corrplot.mixed(datamat1, upper = 'number', lower = 'ellipse', addCoef.col = 1, bg = "white", addgrid.col = "grey")


ggboxplot(Biomarker_Data2, x = "Cognitive_Status" , y = "pT181", color = "Cognitive_Status" ,  palette = c("#00AFBB", "#E7B800", "#FC4E07"), order = c("Cognitively unimpaired", "MCI", "AD"), ylab = "pT181", xlab = "Cognitive Status", remove = NA) + stat_compare_means(method = "t.test", ref.group = "Cognitively unimpaired") + ggtitle("Boxplot of pT181")


##### Q-Q Plots: 

library(ggplot2)
library(tidyr)
library(purrr)
library(qqplotr)

Biomarker_Data21 = pivot_longer(Biomarker_Data2, cols = c(2,3,4,5,6, 7,8, 9, 11))
my_qqplott = function(.data, .title) {
  ggplot(data= .data, mapping = aes(sample = value)) + stat_qq_band(alpha = 0.05) + stat_qq_line()  + stat_qq_point() + facet_wrap(~ name, scales = "free") + 
    labs(x = "Theoretical Quantiles", y = "Sample Quantiles", title = .title)
}
qqplots = Biomarker_Data21 %>% split(.$name) %>% imap(my_qqplott)

qqplots$aBeta40



##### Forest Plot

library(ggplot2)
library(metafor)
library(ggpubr)
library(dplyr)
```

Forest_plot_data = Biomarker_Dataa %>% dplyr::select( pT181, pT217, APOE_Coll, BMI, Age, Race, sex,  Education_Coll, GFAP, NfL,tau, aBeta42, aBeta40, ratio_of_aB42_and_40, ratio_of_p181_and_aB42, Stroke,	Cancer,	Diabetes,	MI, `Depression in last 2yrs`,	Hypertension,	Hypercholesterolemia,	`Sleep Apnea`,`Atrial Fibrillation`)
Forest_plot_data[1 : 2] <- as.data.frame(scale(Forest_plot_data[1 : 2]))
#model
model_pT181 = lm(pT181 ~ APOE_Coll + BMI + Age + Race + sex +  Education_Coll + GFAP+ NfL + tau + aBeta42 + aBeta40 + ratio_of_aB42_and_40 + ratio_of_p181_and_aB42 + Stroke +	Cancer +	Diabetes +	MI + `Depression in last 2yrs`+	Hypertension +	Hypercholesterolemia +	`Sleep Apnea` +	`Atrial Fibrillation`, data = Forest_plot_data)
model_pT217 = lm(pT217 ~ APOE_Coll + BMI + Age + Race + sex +  Education_Coll + GFAP+ NfL + tau + aBeta42 + aBeta40 + ratio_of_aB42_and_40 + ratio_of_p181_and_aB42 + Stroke +	Cancer +	Diabetes +	MI + `Depression in last 2yrs`+	Hypertension +	Hypercholesterolemia +	`Sleep Apnea` +	`Atrial Fibrillation`, data = Forest_plot_data)


coef_pT181 = coef(summary(model_pT181))
coef_pT217 = coef(summary(model_pT217))
#coef_pT181 = coef_pT181[- "(Intercept)"]
coef_pT181 = coef_pT181[- 1,]
coef_pT217 = coef_pT217[- 1,]

forest_data1 = data.frame(
  Variable = rownames(coef_pT181),
  coef_pTau181 = coef_pT181[,"Estimate"],
  SE_pTau181 = coef_pT181[,"Std. Error"],
  P_pTau181 = coef_pT181[,"Pr(>|t|)"]
)

forest_data2 = data.frame(
  Variable = rownames(coef_pT217),
  coef_pTau217 = coef_pT217[,"Estimate"],
  SE_pTau217 = coef_pT217[,"Std. Error"],
  P_pTau217 = coef_pT217[,"Pr(>|t|)"]
)
#Create Forest plot

forest_plot1 = ggplot(forest_data1, aes(y = Variable)) + 
  geom_point(aes(x = coef_pTau181, color = "pT181"), size = 1) + geom_errorbarh(aes(xmin = coef_pTau181 - 1.96*SE_pTau181, xmax = coef_pTau181 + 1.96*SE_pTau181, color = "pT181"), height = 0.15)  + scale_color_manual(values = c("pT181" = "blue")) + labs(x = "coefficient", y = "Variable", title = "Forest Plot of Association", subtitle = "Z score of pT181", caption = "(Mean) 95% Confidence Intervals") +  theme_minimal()
#+ geom_point(aes(x = coef_pTau217, color = "pT217"), size = 1) + geom_errorbarh(aes(xmin = coef_pTau217 - 1.96*SE_pTau217, xmax = coef_pTau217 + 1.96*SE_pTau217, color = "pT217"), height = 0.15)
# #, "pT217" = "red"
forest_plot2 = ggplot(forest_data2, aes(y = Variable)) + 
  geom_point(aes(x = coef_pTau217, color = "pT217"), size = 1) + geom_errorbarh(aes(xmin = coef_pTau217 - 1.96*SE_pTau217, xmax = coef_pTau217 + 1.96*SE_pTau217, color = "pT217"), height = 0.15)  + scale_color_manual(values = c("pT217" = "red")) + labs(x = "coefficient", y = "Variable", title = "Forest Plot of Association", subtitle = "Z score of pT217", caption = "(Mean) 95% Confidence Intervals") +  theme_minimal()
#forest_plot1 = ggplot(forest_data1, aes(y = Variable)) + 
 # geom_point(aes(x = coef_pTau181, color = "pT181"), size = 1) + geom_errorbarh(aes(xmin = coef_pTau181 - 1.96*SE_pTau181, xmax = coef_pTau181 + 1.96*SE_pTau181, color = "pT181"), height = 0.15) + geom_point(aes(x = coef_pTau217, color = "pT217"), size = 1) + geom_errorbarh(aes(xmin = coef_pTau217 - 1.96*SE_pTau217, xmax = coef_pTau217 + 1.96*SE_pTau217, color = "pT217"), height = 0.15) + scale_color_manual(values = c("pT181" = "blue", "pT217" = "red")) + labs(x = "coefficient", y = "Variable", title = "Forest Plot of Association", subtitle = "Z score of pT181 and pT217", caption = "(Mean) 95% Confidence Intervals") +  theme_minimal()

Figure = ggarrange(forest_plot1, forest_plot2, labels = c("A", "B"), ncol = 2, nrow = 1)
Figure



#### Splitting the data using Cross Validation method: 

#Splitting train and test data
Biomarker_Data11 = Biomarker_Dataa
Biomarker_Dataa = Biomarker_Data11 %>% filter(Cognitive_Status == "Cognitively unimpaired" | Cognitive_Status == "MCI" | Cognitive_Status == "AD") %>% filter(Race == "White" | Race == "Black")
Biomarker_Dataa = na.omit(Biomarker_Dataa)



set.seed(154)
nrFolds = 5
folds = rep_len(1:nrFolds, nrow(Biomarker_Dataa))
folds = sample(folds, nrow(Biomarker_Dataa))
for(k in 1:nrFolds) {
  fold = which(folds == k)
  train1 = Biomarker_Dataa[-fold,]
  test1 = Biomarker_Dataa[fold,]
}

Wh_c = table(Biomarker_Dataa$Cognitive_Status)
Wh_c
tot = sum(Wh_c)
Wh_c/tot

#### Training data
Wh_c_tr = table(train1$Cognitive_Status)
Wh_c_tr
tot_tr = sum(Wh_c_tr)
Wh_c_tr/tot_tr
#split = sample(nrow(Biomarker_Dataa), floor(0.7*nrow(Biomarker_Dataa)))
#train1 = Biomarker_Dataa[split,]
#test1 = Biomarker_Dataa[-split,]
#head(train_data)
#head(test_data)


Wh_c_te = table(test1$Cognitive_Status)
Wh_c_te
tot_te = sum(Wh_c_te)
Wh_c_te/tot_te



##### Model with demographic variables (Age, Race, Sex and Education)
mod_dem = multinom(Cognitive_Status ~ Age + Race + sex + Education_Coll  , data = train1)
summary(mod_dem)
#+ Education_Coll

mod_dem_OR = tbl_regression(mod_dem, exponentiate = TRUE , label = list( Education_Coll ~ "Education")) %>% bold_labels() %>% modify_caption("**Demographic Model :Normal cognition as refrence category**")
mod_dem_OR

##### Overall Prediction and Accuracy
predictions_dem_train <- predict(mod_dem, train1)
predictions_dem_test <- predict(mod_dem, test1)
ta1_train_dem=table(predictions_dem_train, train1$Cognitive_Status)
ta1_train_dem
ta1_test_dem=table(predictions_dem_test, test1$Cognitive_Status)
ta1_test_dem
#Accuracy
train_dem = round((sum(diag(ta1_train_dem))/sum(ta1_train_dem))*100, 2)
test_dem = round((sum(diag(ta1_test_dem))/sum(ta1_test_dem))*100, 2)



##### ROC Curve: How much a model is capable of distinguishing between classes. 
p2 = predict(mod_dem, test1, type = 'class')
confusionMatrix(p2, test1$Cognitive_Status)
p2 = predict(mod_dem, test1, type = 'prob')
r = multiclass.roc(test1$Cognitive_Status, p2, percent = T)
rs4 = r[['rocs']]
CU_MCI = rs4[[1]][[2]]
CU_AD = rs4[[2]][[2]]
Ad_MCI = rs4[[3]][[2]]
plot.roc(CU_AD, col = 'blue', main = 'ROC Curve for Demographic model')
plot.roc(Ad_MCI, add = T, col = 'red')
plot.roc(CU_MCI, add = T, col = 'green')
legend("topright", c("CU_AD", "Ad_MCI", "CU_MCI"), lty=1,col = c("blue", "red", "green"), bty = "n")


CognitivelyUnimpaired_AD = auc(CU_AD)
AD_MCI = auc(Ad_MCI)
CognitivelyUnimpaired_MCI = auc(CU_MCI)
AUC = rbind(CognitivelyUnimpaired_AD, CognitivelyUnimpaired_MCI,AD_MCI )
colnames(AUC) = c("AUC")
AUC 





















##### Model with demographic variables, pT217, pT181, and GFAP

```{r, echo=FALSE, warning=FALSE, message=FALSE}
mod_dem11 = multinom(Cognitive_Status ~ Age + Race + sex + Education_Coll  + pT217 + pT181 + GFAP, data = train1)
summary(mod_dem11)

mod_dem11_OR = tbl_regression(mod_dem11, exponentiate = TRUE , label = list( Education_Coll ~ "Education")) %>% bold_labels() %>% modify_caption("**Demographic + pT217 + pT181 + GFAP Model**")
mod_dem11_OR


##### Forest Plot:

OR = exp(coef(mod_dem11))
OR = data.frame(OR)
OR_transpose = t(OR)
CI = exp(confint(mod_dem11))
CI = data.frame(CI)
OR_CI_MCI = data.frame(round(cbind(OR_transpose[,1], CI[,c(1,2)]), 3))
OR_CI_MCI = OR_CI_MCI %>% mutate(variable = rownames(OR_CI_MCI))
#colnames(data.frame(OR_CI_MCI))
OR_CI_MCI = rename(OR_CI_MCI, c("AOR_MCI" = "OR_transpose...1." , "lower_bound" = "X2.5...MCI" , "upper_bound" = "X97.5...MCI" ))
col_order1 = c("variable", "AOR_MCI", "lower_bound","upper_bound" )
OR_CI_MCI = OR_CI_MCI[, col_order1]
plot1 = OR_CI_MCI[-1,] %>% ggplot(aes(x = reorder(variable, AOR_MCI), y = AOR_MCI)) +
  geom_point(, shape = 20, size = 4, color = "black") + 
  geom_errorbar(aes(ymin = lower_bound, ymax = upper_bound, width = 0.5, color = "darkgreen")) + coord_flip()
plot1 + geom_hline(yintercept = 1, color = "red")





##### Prediction and Accuracy


predictions_dem11_train <- predict(mod_dem11, train1)
predictions_dem11_test <- predict(mod_dem11, test1)
ta1_train_dem11=table(predictions_dem11_train, train1$Cognitive_Status)
ta1_train_dem11
ta1_test_dem11=table(predictions_dem11_test, test1$Cognitive_Status)
ta1_test_dem11
#Accuracy
train_dem11 = round((sum(diag(ta1_train_dem11))/sum(ta1_train_dem11))*100, 2)
test_dem11 = round((sum(diag(ta1_test_dem11))/sum(ta1_test_dem11))*100, 2)


round(train_dem11,0)
round(test_dem11,0)
```



##### ROC Curve:



p11 = predict(mod_dem11, test1, type = 'class')
confusionMatrix(p11, test1$Cognitive_Status)
p11 = predict(mod_dem11, test1, type = 'prob')
r = multiclass.roc(test1$Cognitive_Status, p11, percent = T)
rs11 = r[['rocs']]
CU_MCI = rs11[[1]][[2]]
CU_AD = rs11[[2]][[2]]
Ad_MCI = rs11[[3]][[2]]
plot.roc(CU_AD, col = 'blue', main = 'ROC Curve for Demographic + pT217 +  pT181 + GFAP model')
plot.roc(Ad_MCI, add = T, col = 'red')
plot.roc(CU_MCI, add = T, col = 'green')
legend("topright", c("CU_AD", "Ad_MCI", "CU_MCI"), lty=1,col = c("blue", "red", "green"), bty = "n")
CognitivelyUnimpaired_AD = round(auc(CU_AD),0)
AD_MCI = round(auc(Ad_MCI),0)
CognitivelyUnimpaired_MCI = round(auc(CU_MCI),0)
AUC = rbind(CognitivelyUnimpaired_AD, CognitivelyUnimpaired_MCI,AD_MCI )
colnames(AUC) = c("AUC")
AUC 

CU_MCI
CU_AD
Ad_MCI







##### Stepwise Regression with backward Selection: 


require(nnet)
library(tidyverse)
library(caret)
library(MASS)
train1= na.omit(train1)
#intercept_only <- multinom(Cognitive_Status ~ 1, data=train1)
mod1 = multinom(Cognitive_Status ~ pT217  + tau + pT181 + GFAP +  NfL + APOE_Coll + + ratio_of_aB42_and_40 + Education_Coll + Age + BMI + sex + Race, data = train1)
#summary(mod1)

##### Odds Ratio and 95 \% CI

Step_model = tbl_regression(mod_step, exponentiate = TRUE) %>% bold_labels() %>% modify_caption("**Stepwise Model: Backward selection**")
Step_model



##### Prediction and Accuracy

predictions_train_f <- predict(mod_step, train1)
predictions_test_f <- predict(mod_step, test1)
ta1_train=table(predictions_train_f, train1$Cognitive_Status)
ta1_test=table(predictions_test_f, test1$Cognitive_Status)
mod_step_predictions_train <- predict(mod_step, train1)
mod_step_predictions_test <- predict(mod_step, test1)
step_ta1_train=table(mod_step_predictions_train, train1$Cognitive_Status)
step_ta1_train
step_ta1_test=table(mod_step_predictions_test, test1$Cognitive_Status)
step_ta1_test

#Accuracy
#round((sum(diag(ta1_train))/sum(ta1_train))*100, 2)
train_st = round((sum(diag(step_ta1_train))/sum(step_ta1_train))*100, 2)
#round((sum(diag(ta1_test))/sum(ta1_test))*100, 2)
test_st = round((sum(diag(step_ta1_test))/sum(step_ta1_test))*100, 2)
```


##### ROC Curve for Stepwise model:


library(pROC)
p3 = predict(mod_step, test1, type = 'class')
confusionMatrix(p3, test1$Cognitive_Status)
p3 = predict(mod_step, test1, type = 'prob')
r = multiclass.roc(test1$Cognitive_Status, p3, percent = T)
rs3 = r[['rocs']]
CU_MCI = rs3[[1]][[2]]
CU_AD = rs3[[2]][[2]]
Ad_MCI = rs3[[3]][[2]]
plot.roc(CU_AD, col = 'blue', main = 'ROC Curve for Stepwise model')
plot.roc(Ad_MCI, add = T, col = 'red')
plot.roc(CU_MCI, add = T, col = 'green')
legend("topright", c("CU_AD", "Ad_MCI", "CU_MCI"), lty=1,col = c("blue", "red", "green"), bty = "n")
CognitivelyUnimpaired_AD = round(auc(CU_AD), 1)
AD_MCI = round(auc(Ad_MCI), 1)
CognitivelyUnimpaired_MCI = round(auc(CU_MCI), 1)


##### AUC

AUC = rbind(CognitivelyUnimpaired_AD, CognitivelyUnimpaired_MCI,AD_MCI )
colnames(AUC) = c("AUC")
AUC 





##### Stepwise Regression with both Selection: 

`
require(nnet)
library(tidyverse)
library(caret)
library(MASS)
train1= na.omit(train1)
#intercept_only <- multinom(Cognitive_Status ~ 1, data=train1)
mod2 = multinom(Cognitive_Status ~ pT217  + tau + pT181  + GFAP +  NfL + APOE_Coll + Education_Coll + Age + BMI + sex + Race, data = train1)



mod_step = stepAIC(mod2, direction = "both", trace = T)
summary(mod_step)

##### Odds Ratio and 95 \% CI

Step_model = tbl_regression(mod_step, exponentiate = TRUE) %>% bold_labels() %>% modify_caption("**Stepwise Model: both selection**")
Step_model





##### Prediction and Accuracy


predictions_train_f <- predict(mod_step, train1)
predictions_test_f <- predict(mod_step, test1)
ta1_train=table(predictions_train_f, train1$Cognitive_Status)
ta1_test=table(predictions_test_f, test1$Cognitive_Status)
mod_step_predictions_train <- predict(mod_step, train1)
mod_step_predictions_test <- predict(mod_step, test1)
step_ta1_train=table(mod_step_predictions_train, train1$Cognitive_Status)
step_ta1_train
step_ta1_test=table(mod_step_predictions_test, test1$Cognitive_Status)
step_ta1_test



##### Validation with train and test data

#Accuracy
#round((sum(diag(ta1_train))/sum(ta1_train))*100, 2)
train_st = round((sum(diag(step_ta1_train))/sum(step_ta1_train))*100, 2)
#round((sum(diag(ta1_test))/sum(ta1_test))*100, 2)
test_st = round((sum(diag(step_ta1_test))/sum(step_ta1_test))*100, 2)



##### ROC Curve for Stepwise model:


library(pROC)
p3 = predict(mod_step, test1, type = 'class')
confusionMatrix(p3, test1$Cognitive_Status)
p3 = predict(mod_step, test1, type = 'prob')
r = multiclass.roc(test1$Cognitive_Status, p3, percent = T)
rs3 = r[['rocs']]
CU_MCI = rs3[[1]][[2]]
CU_AD = rs3[[2]][[2]]
Ad_MCI = rs3[[3]][[2]]
plot.roc(CU_AD, col = 'blue', main = 'ROC Curve for Stepwise model')
plot.roc(Ad_MCI, add = T, col = 'red')
plot.roc(CU_MCI, add = T, col = 'green')
legend("topright", c("CU_AD", "Ad_MCI", "CU_MCI"), lty=1,col = c("blue", "red", "green"), bty = "n")
CognitivelyUnimpaired_AD = round(auc(CU_AD),0)
AD_MCI = round(auc(Ad_MCI),0)
CognitivelyUnimpaired_MCI = round(auc(CU_MCI),0)


##### AUC

AUC = rbind(CognitivelyUnimpaired_AD, CognitivelyUnimpaired_MCI,AD_MCI )
colnames(AUC) = c("AUC")
AUC 













